---
apiVersion: v1
kind: ConfigMap
metadata:
  namespace: homelab-monitoring
  name: telegraf-realtime-config-map
data:
  telegraf-realtime.conf: |
    [[inputs.vsphere]]
      alias = "vsphere-realtime"
      interval = "60s"
      vcenters = [ "https://vcsa.homelab/sdk" ]
      insecure_skip_verify = true
      username = "$VSPHERE_USER"
      password = "$VSPHERE_PASSWORD"

      max_query_metrics = 256
      collect_concurrency = 1
      discover_concurrency = 1

      vm_metric_include = ["*"]
      host_metric_include = ["*"]

      cluster_metric_exclude = ["*"]
      datacenter_metric_exclude = ["*"]
      resource_pool_metric_exclude = ["*"]
      vsan_metric_exclude = ["*"]

    [[outputs.prometheus_client]]
      listen = ":9273"    
      # expiration_interval = "120s"

      metric_buffer_limit = 1000

---
apiVersion: v1
kind: ConfigMap
metadata:
  namespace: homelab-monitoring
  name: telegraf-historical-config-map
data:
  telegraf-historical.conf: |
    [[inputs.vsphere]]
      alias = "vsphere-historical"
      interval = "300s"
      vcenters = [ "https://vcsa.homelab/sdk" ]
      insecure_skip_verify = true
      username = "$VSPHERE_USER"
      password = "$VSPHERE_PASSWORD"

      max_query_metrics = 256
      collect_concurrency = 1
      discover_concurrency = 1

      vm_metric_exclude = ["*"]
      host_metric_exclude = ["*"]
      datastore_metric_exclude = ["*"]
      datacenter_metric_exclude = ["*"]
      cluster_metric_exclude = ["*"]
      vsan_metric_exclude = [ "*" ]

    [[outputs.prometheus_client]]
      listen = ":9274"    
      expiration_interval = "120s"

      metric_buffer_limit = 1000

# deploy the container itself
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: homelab-monitoring
  name: telegraf
spec:
  selector:
    matchLabels:
      app: telegraf
  minReadySeconds: 5
  template:
    metadata:
      labels:
        app: telegraf
    spec:
      containers:
        - image: telegraf:1.28.5
          name: telegraf
          volumeMounts:
            - mountPath: /etc/telegraf/telegraf.d/telegraf-realtime.conf
              name: telegraf-realtime-config-map
              subPath: telegraf-realtime.conf
              readOnly: true
            - mountPath: /etc/telegraf/telegraf.d/telegraf-historical.conf
              name: telegraf-historical-config-map
              subPath: telegraf-historical.conf
              readOnly: true
          env:
            - name: VSPHERE_USER
              valueFrom:
                secretKeyRef:
                  name: telegraf-secrets
                  key: username.txt
            - name: VSPHERE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: telegraf-secrets
                  key: password.txt
      volumes:
        - name: telegraf-realtime-config-map
          configMap:
            name: telegraf-realtime-config-map
        - name: telegraf-historical-config-map
          configMap:
            name: telegraf-historical-config-map

#expose a service in k8s so Prometheus can reach Telegraf
---
apiVersion: v1
kind: Service
metadata:
  name: telegraf-service
  namespace: homelab-monitoring
spec:
  selector:
    app: telegraf
  ports:
    - name: realtime
      protocol: TCP
      port: 9273
      targetPort: 9273
    - name: historical
      protocol: TCP
      port: 9274
      targetPort: 9274
