---
apiVersion: v1
kind: ConfigMap
metadata:
  name: telegraf-config-map
data:
  telegraf.conf: |
    [[inputs.vsphere]]
      interval = "20s"
      vcenters = [ "https://vcsa.homelab/sdk" ]
      username = $VSPHERE_USER
      password = $VSPHERE_PASSWORD

      insecure_skip_verify = true
      force_discover_on_init = true

      collect_concurrency = 1
      discover_concurrency = 1

      vm_metric_include = ["*"]
      host_metric_include = ["*"]

      cluster_metric_exclude = ["*"]
      datastore_metric_exclude = ["*"]
      datacenter_metric_exclude = ["*"]
    
    [[inputs.vsphere]]
      interval = "300s"

      vcenters = [ "https://vcsa.homelab/sdk" ]
      username = $VSPHERE_USER
      password = $VSPHERE_PASSWORD

      insecure_skip_verify = true
      force_discover_on_init = true

      host_metric_exclude = ["*"]
      vm_metric_exclude = ["*"]

      max_query_metrics = 256
      collect_concurrency = 1

    [[outputs.prometheus_client]]
      listen = ":9273"    
      expiration_interval = "60s"

      ## Export metric collection time.
      # export_timestamp = false

# deploy the container itself
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: telegraf-deployment
  labels:
    app: telegraf
spec:
  template:
    spec:
      containers:
        - image: telegraf:latest
          name: telegraf
          ports:
            - containerPort: 
          volumeMounts:
            - mountPath: /etc/telegraf/telegraf.conf
              name: telegraf-config-map
          
          env:
            - name: VSPHERE_USER
              valueFrom:
                secretKeyRef:
                  name: telegraf-secrets
                  key: username.txt
            - name: VSPHERE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: telegraf-secrets
                  key: password.txt
      volumes:
            - name: telegraf-config-map
              configMap:
                name: telegraf-config-map

#expose a service in k8s so Prometheus can reach Telegraf
---
apiVersion: v1
kind: Service
metadata:
  name: telegraf-service
spec:
  selector:
    app: telegraf
  ports:
    - protocol: TCP
      port: 9273
      targetPort: 9273
