---
secrets

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: telegraf-config-map
data:
  telegraf.conf: |
    [[inputs.vsphere]]
      interval = "20s"
      vcenters = [ "https://vcsa.homelab/sdk" ]
      username = ""
      password = ""

      insecure_skip_verify = true
      force_discover_on_init = true

      collect_concurrency = 1
      discover_concurrency = 1

      vm_metric_include = ["*"]
      host_metric_include = ["*"]

      cluster_metric_exclude = ["*"]
      datastore_metric_exclude = ["*"]
      datacenter_metric_exclude = ["*"]
    
    [[inputs.vsphere]]
      interval = "300s"

      vcenters = [ "https://vcsa.homelab/sdk" ]
      username = ""
      password = ""

      insecure_skip_verify = true
      force_discover_on_init = true

      host_metric_exclude = ["*"] # Exclude realtime metrics
      vm_metric_exclude = ["*"] # Exclude realtime metrics

      max_query_metrics = 256
      collect_concurrency = 1

    [[outputs.prometheus_client]]
      listen = ":9273"    
      expiration_interval = "60s"

      ## Export metric collection time.
      # export_timestamp = false

---
# app deployment
config filepath: /etc/telegraf/telegraf.conf
