---
apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config-map
  namespace: homelab-monitoring
data:
  homelab.yml: |
    global:
      scrape_interval:     15s
      evaluation_interval: 15s
    scrape_configs:
      - job_name: 'telegraf'
        static_configs:
        - targets: ['telegraf-service:9273']

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: prom-pv-volume
  namespace: homelab-monitoring
spec:
  capacity:
    storage: 1Gi
  storageClassName: local-storage
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data"

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: prometheus
  namespace: homelab-monitoring
  labels:
    app.kubernetes.io/name: prometheus
spec:
  replicas: 1
  updateStrategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app.kubernetes.io/name: prometheus
  template:
    metadata:
      name: prometheus
      labels:
        app.kubernetes.io/name: prometheus
    spec:
      initContainers:
        - name: prometheus-data-permission-fix
          image: busybox
          command: ["/bin/chmod","-R","777", "/data"]
          volumeMounts:
          - name: prom-pv-volume
            mountPath: /data
      containers:
        - name: prometheus
          image: prom/prometheus
          args:
            - "--storage.tsdb.path=/data"
            - "--storage.tsdb.retention.size=900MB"
            - "--config.file=/etc/prometheus/homelab.yml"
          ports:
            - containerPort: 9090
          volumeMounts:
            - name: prom-config-volume
              mountPath: /etc/prometheus
            - name: prom-pv-volume
              mountPath: /data
      volumes:
        - name: prom-config-volume
          configMap:
            name: prometheus-config-map
  volumeClaimTemplates:
  - metadata:
      name: prom-pv-volume
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 1Gi
      storageClassName: "local-storage"

---
apiVersion: v1
kind: Service
metadata:
  name: prom-service
  namespace: homelab-monitoring
spec:
  selector:
    app.kubernetes.io/name: prometheus
  type: NodePort
  ports:
    - protocol: TCP
      port: 443
      targetPort: 9090

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: prom-ingress
spec:
  rules:
  - http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: prom-service
            port:
              number: 443

# ---
# apiVersion: gateway.networking.k8s.io/v1
# kind: GatewayClass
# metadata:
#   name: prom-class
#   namespace: homelab-monitoring
# spec:
#   controllerName: prom.kubes.homelab/gateway-controller

# ---
# apiVersion: gateway.networking.k8s.io/v1
# kind: Gateway
# metadata:
#   name: prom-gateway
#   namespace: homelab-monitoring
# spec:
#   gatewayClassName: prom-class
#   listeners:
#   - name: http
#     protocol: HTTP
#     port: 443

# ---
# apiVersion: gateway.networking.k8s.io/v1
# kind: HTTPRoute
# metadata:
#   name: prom-httproute
#   namespace: homelab-monitoring
# spec:
#   parentRefs:
#   - name: prom-gateway
#   hostnames:
#   - "prom.kubes.homelab"
#   rules:
#   - matches:
#     backendRefs:
#     - name: prom-service
#       port: 9090
