---
apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config-map
  namespace: homelab-monitoring
data:
  homelab.yml: |
    global:
      scrape_interval:     15s
      evaluation_interval: 15s
    scrape_configs:
      - job_name: 'telegraf'
        static_configs:
        - targets: ['telegraf-service:9273']

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: prometheus
  namespace: homelab-monitoring
  labels:
    k8s-app: prometheus
spec:
  replicas: 1
  selector:
    matchLabels:
      k8s-app: prometheus
  template:
    metadata:
      name: prometheus
      labels:
        k8s-app: prometheus
    spec:
      containers:
        - name: prometheus
          image: prom/prometheus
          args:
            - "--storage.tsdb.retention.time=7d"
            - "--config.file=/etc/prometheus/homelab.yml"
          ports:
            - containerPort: 9090
          volumeMounts:
          - name: prom-config-volume
            mountPath: /etc/prometheus/
      volumes:
        - name: prom-config-volume
          configMap:
            name: prometheus-config-map
# todo: add volume mount for data persistence

---
apiVersion: v1
kind: Service
metadata:
  name: prom-service
  namespace: homelab-monitoring
spec:
  selector:
    app.kubernetes.io/name: prometheus
  ports:
    - protocol: TCP
      port: 9090
      targetPort: 9090

---
apiVersion: gateway.networking.k8s.io/v1
kind: GatewayClass
metadata:
  name: prom-class
  namespace: homelab-monitoring
spec:
  controllerName: prom.kubes.homelab/gateway-controller

---
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: prom-gateway
  namespace: homelab-monitoring
spec:
  gatewayClassName: prom-class
  listeners:
  - name: http
    protocol: HTTP
    port: 443

---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: prom-httproute
  namespace: homelab-monitoring
spec:
  parentRefs:
  - name: prom-gateway
  hostnames:
  - "prom.kubes.homelab"
  rules:
  - matches:
    backendRefs:
    - name: prom-service
      port: 9090
