---
apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config-map
  namespace: homelab-monitoring
data:
  prometheus.yml: |
    global:
      scrape_interval:     15s
      evaluation_interval: 15s
    scrape_configs:
      - job_name: 'telegraf'
        static_configs:
        - targets: ['telegraf-service:9273']

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: prometheus
  namespace: homelab-monitoring
  labels:
    k8s-app: prometheus
spec:
  replicas: 1
  selector:
    matchLabels:
      k8s-app: prometheus
  template:
    metadata:
      name: prometheus
      labels:
        k8s-app: prometheus
    spec:
      containers:
        - name: prometheus
          image: prom/prometheus
          args:
            - "--storage.tsdb.retention.time=7d"
          ports:
            - containerPort: 9090
# todo: config map
# todo: add volume mount for data persistence

---
apiVersion: v1
kind: Service
metadata:
  name: prom-service
  namespace: homelab-monitoring
spec:
  selector:
    app.kubernetes.io/name: prometheus
  ports:
    - protocol: TCP
      port: 443
      targetPort: 9090

# ---
# apiVersion: networking.k8s.io/v1
# kind: Ingress
# metadata:
#   name: prom-ingress
#   namespace: homelab-monitoring
# spec:
#   rules:
#     - host: prom.kubes.homelab
#       http:
#         paths:
#         - backend:
#           serviceName: prom-service
#           servicePort: 9090
