---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: synology-nfs
  annotations:
    storageclass.kubernetes.io/is-default-class: "true"
provisioner: nfs.csi.k8s.io
volumeBindingMode: WaitForFirstConsumer
reclaimPolicy: Delete
mountOptions:
  - nfsvers=4.1
parameters:
  server: synology.homelab
  share: /volume1/kubernetes
